services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      KAFKA_MESSAGE_MAX_BYTES: 31457280
      KAFKA_REPLICA_FETCH_MAX_BYTES: 31457280
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 5s
      timeout: 5s
      retries: 10  

    volumes:
      - kafka_kraft:/var/lib/kafka/data
  Intelligence_information_targets:
      build: /Intelligence_information_targets
      environment: 
          KAFKA_URI: kafka:9092

  test:
    build: /students_part_1        
volumes:
   kafka_kraft:
  